{
 "title": "Airflow Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Task Instances Successes & Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(airflow_ti_successes[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "increase(airflow_ti_failures[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Scheduler Heartbeat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat[10m])*60",
     "legendFormat": "Heartbeats per Minute"
    }
   ]
  },
  {
   "title": "Scheduler Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_executable",
     "legendFormat": "Executable"
    },
    {
     "expr": "airflow_scheduler_tasks_pending",
     "legendFormat": "Pending"
    },
    {
     "expr": "airflow_scheduler_tasks_running",
     "legendFormat": "Running"
    },
    {
     "expr": "airflow_scheduler_tasks_starving",
     "legendFormat": "Starving"
    },
    {
     "expr": "airflow_scheduler_tasks_killed_externally",
     "legendFormat": "Killed Externally"
    },
    {
     "expr": "airflow_scheduler_tasks_without_dagrun",
     "legendFormat": "Without DagRun"
    }
   ]
  },
  {
   "title": "Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_executor_open_slots", "legendFormat": "Open Slots" },
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Queued Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Running Tasks" }
   ]
  },
  {
   "title": "DagBag Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_dagbag_size", "legendFormat": "DagBag Size" }
   ]
  }
 ]
}